CORRECTION_HTML = r"""<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Correct transcript</title><style>
:root{font-family:Inter,"Segoe UI",system-ui,sans-serif;color:#17201d}body{background:#f2f5f4;margin:0}main{width:min(1150px,calc(100% - 28px));margin:22px auto}.card{background:white;border:1px solid #dce5e2;border-radius:15px;padding:18px;margin-top:12px}.tags{display:grid;grid-template-columns:1fr 1fr;gap:10px;margin:10px 0}.attach{display:grid;grid-template-columns:1fr 180px;gap:10px;margin:10px 0}.row{display:grid;grid-template-columns:90px 90px 140px 80px 1fr 40px;gap:8px;margin:8px 0}input,textarea,button,select{box-sizing:border-box;width:100%;padding:8px;border:1px solid #bdcbc7;border-radius:8px;font:inherit}textarea{min-height:60px}button{border:0;background:#196b59;color:white;font-weight:700}.danger{background:#8a3333}audio{width:100%}.help{color:#53635e;font-size:.88rem}.check{display:flex;gap:8px;align-items:center;margin:12px 0}.check input{width:auto}a{color:#145d4e;font-weight:700}@media(max-width:750px){.row,.tags,.attach{grid-template-columns:1fr}}
</style></head><body><main><a href="/">← Main transcriber</a><section class="card">
<h1>Correct transcript</h1>
<p>Listen, correct the exact spoken words and speakers, and save locally. Held-out calls are used only to measure accuracy and are never used for training.</p>
<audio id="audio" controls></audio>
<div class="attach"><input id="audioFile" type="file" accept="audio/*,video/*"><button id="attachAudio">Attach original audio</button></div>
<p class="help">Attach the matching original recording if the app did not retain its upload copy. It is converted to a private lossless WAV and never uploaded.</p>
<label class="check"><input id="heldOut" type="checkbox"> Held-out evaluation reference (never training data)</label>
<div class="tags"><label>Dialect<select id="dialect"><option>Hindi + dialect</option><option>Mostly Hindi</option><option>Haryanvi-influenced</option><option>Rajasthani-influenced</option><option>Hindi + English code-mix</option></select></label><label>Audio condition<select id="noise"><option>Telephone narrowband</option><option>Clean</option><option>Noisy</option><option>Reverberant</option></select></label></div>
<p id="status" class="help">Loading…</p>
<div class="row help"><b>Start</b><b>End</b><b>Speaker</b><b>Overlap</b><b>Verbatim words</b><b></b></div><div id="rows"></div><button id="add">Add segment</button>
</section></main><script>
const file=decodeURIComponent(location.pathname.split('/').pop()),$=id=>document.getElementById(id);let data,rows=[],timer;
function render(){const root=$('rows');root.replaceChildren();rows.forEach((row,index)=>{const div=document.createElement('div');div.className='row';for(const field of ['start','end']){const input=document.createElement('input');input.type='number';input.step='.001';input.value=Number(row[field]).toFixed(3);input.oninput=()=>{row[field]=Number(input.value);saveLater()};div.appendChild(input)}const speaker=document.createElement('input');speaker.value=row.speaker||'';speaker.oninput=()=>{row.speaker=speaker.value;saveLater()};div.appendChild(speaker);const overlap=document.createElement('input');overlap.type='checkbox';overlap.checked=!!row.overlap;overlap.onchange=()=>{row.overlap=overlap.checked;saveLater()};div.appendChild(overlap);const words=document.createElement('textarea');words.value=row.text||'';words.onfocus=()=>{if($('audio').readyState)$('audio').currentTime=Math.max(0,row.start-.25)};words.ondblclick=()=>{$('audio').currentTime=Math.max(0,row.start-.25);$('audio').play()};words.oninput=()=>{row.text=words.value;saveLater()};div.appendChild(words);const remove=document.createElement('button');remove.textContent='×';remove.className='danger';remove.onclick=()=>{rows.splice(index,1);render();saveLater()};div.appendChild(remove);root.appendChild(div)})}
function saveLater(){clearTimeout(timer);timer=setTimeout(save,500)}
async function save(){const response=await fetch('/api/corrections/'+encodeURIComponent(file),{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({segments:rows,held_out:$('heldOut').checked,tags:{dialect:$('dialect').value,noise:$('noise').value}})});const p=await response.json();$('status').textContent=response.ok?($('heldOut').checked?'Saved as held-out evaluation data.':'Saved locally for personal adaptation.'):p.error}
$('attachAudio').onclick=async()=>{const selected=$('audioFile').files[0];if(!selected){$('status').textContent='Choose the matching original recording first.';return}const form=new FormData();form.append('audio',selected);$('status').textContent='Checking and attaching the original audio…';const response=await fetch('/api/corrections/'+encodeURIComponent(file)+'/audio',{method:'POST',body:form});const p=await response.json();if(response.ok){$('audio').src='/correction-audio/'+encodeURIComponent(file)+'?v='+Date.now();$('status').textContent='Original audio attached locally.'}else{$('status').textContent=p.error||'Audio attachment failed.'}}
$('add').onclick=()=>{const p=rows.at(-1),start=p?p.end:0;rows.push({start,end:Math.min(data.duration_seconds,start+5),speaker:p?.speaker||'Speaker 1',text:''});render()};
document.addEventListener('keydown',event=>{if(event.code==='Space'&&event.target.tagName!=='TEXTAREA'&&event.target.tagName!=='INPUT'){event.preventDefault();$('audio').paused?$('audio').play():$('audio').pause()}});
fetch('/api/corrections/'+encodeURIComponent(file)).then(async response=>{const p=await response.json();if(!response.ok)throw Error(p.error);data=p;rows=p.segments||[];if(p.correction_metadata?.tags){$('dialect').value=p.correction_metadata.tags.dialect||$('dialect').value;$('noise').value=p.correction_metadata.tags.noise||$('noise').value}$('heldOut').checked=!!p.correction_metadata?.held_out;$('dialect').onchange=saveLater;$('noise').onchange=saveLater;$('heldOut').onchange=saveLater;if(p.audio_available)$('audio').src='/correction-audio/'+encodeURIComponent(file);render();$('status').textContent=p.audio_available?'Double-click a text box to play that turn; Space pauses or resumes.':'Attach the original recording above to listen while correcting.'}).catch(error=>$('status').textContent=error.message);
</script></body></html>"""
